name: Build Android APK
    2
    3     on:
    4       push:
    5         branches: [ "main" ]
    6       workflow_dispatch:
    7
    8     jobs:
    9       build:
   10         runs-on: ubuntu-latest
   11
   12         steps:
   13           - name: Checkout repository
   14             uses: actions/checkout@v4
   15
   16           - name: Set up JDK 17
   17             uses: actions/setup-java@v4
   18             with:
   19               java-version: '17'
   20               distribution: 'temurin'
   21
   22           - name: Build with Gradle
   23             uses: gradle/actions/setup-gradle@v3
   24             with:
   25               gradle-version: '8.7'
   26               arguments: assembleDebug
   27
   28           - name: Upload APK
   29             uses: actions/upload-artifact@v4
   30             with:
   31               name: mfdc-cheat-apk
   32               path: app/build/outputs/apk/debug/app-debug.apk
